; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:genericSTM32F103C8]
platform = ststm32
board = genericSTM32F103C8
framework = stm32cube

upload_protocol = stlink
; upload_resetmethod = default

debug_tool = stlink
debug_extra_cmds = monitor reset run
monitor_speed = 115200

build_flags =
    -O3
    -ffast-math
    -fsingle-precision-constant
    --specs=nano.specs
    -fno-strict-aliasing -fno-optimize-sibling-calls
    -Wl,-u,_printf_float    
    
    -DHSE_VALUE=8000000U
    -DUSE_HAL_DRIVER
    -DHAL_NVIC_MODULE_ENABLED

    -I src/Core/Inc

